### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by chase** [fantaye-1/man_pac#26]
There is duplicated code between `ghost.c` and `manpac.c`.
To reduce our line count, we should refactor the shared code into a `shared.c` file, add the function protoypes to `shared.h`.
The original behavior should be maintained.

**Comment by yashito** [comment]
Merging attempt was made by merging `window_loop()` as well as moving all the functions referenced in `window_loop()` to `shared.c`. However, running `manpac` gives segmentation fault.

I'm suspecting that casting void pointer caused issue somewhere within `shared.c`.

Note that in `shared.c`, merging attempt was made by generalizing `ghost_t` and `shared_t` structs with void pointer, and casting them with the control of a flag called `struct_type` as a form of a parameter received by `window_loop()`.
Since now `shared.c` includes functions that were used to be exclusive to each `ghost.c` and `manpac.c`, I couldn't keep such functions there but had to move to `shared.c` to make them get compiled.
